# Generated by Django 4.0.4 on 2022-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
