# Generated by Django 4.0.4 on 2022-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_no',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
