# Generated by Django 4.0.4 on 2022-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='My_Orders',
        ),
        migrations.AlterModelTable(
            name='my_orders',
            table='my_orders',
        ),
    ]
