# Generated by Django 4.0.4 on 2022-06-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
